- name: Automatizar la creación de un EE
  hosts: localhost
  connection: local
  tasks:
    - name: Crear el archivo requirements.yml
      copy:
        dest: ./requirements.yml
        content: |
          ---
          collections:
            - name: community.general
              version: "5.2.0"
      

    - name: Crear el archivo execution-environment.yml
      copy:
        dest: ./execution-environment.yml
        content: |
          version: 3
          dependencies:
            galaxy: requirements.yml
            system: bindep.txt
  
    - name: Ejecutar ansible-builder para crear el EE
      ansible.builtin.command:
        cmd: ${HOME}/.local/bin/ansible-builder build --tag ansible-pah.liverpool.com.mx/liverpool/custom-ee:latest -v3
                                 #ansible-builder build -t ansible-pah.liverpool.com.mx/liverpool/custom-ee:latest -v3
        chdir: "/var"
    

    - name: Verificar que la imagen se creó correctamente
      ansible.builtin.command:
        cmd: podman images | grep custom-ee
      register: ee_image_check
     

    - name: Subir la imagen al registro de contenedores (opcional)
      ansible.builtin.command:
        cmd: podman push custom-ee:latest registry.example.com/custom-ee:latest
      when: upload_image | default(false)
     
